### ISSUE TITLE
When game starts, it doesnt capture the keyboard. Even when one clicks on the screen.

### ISSUE THREAD

**Issue by rhinoid** [vAmigaWeb/vAmigaWeb#136] opened 2022-11-22 11:59 UTC
I embedded my old game on the web (Amazing that this works btw)
However it doesn't capture the keyboard. Even tapping the gamescreen, it still doesn't do it. 
ONLY when the bottom gray bar is tapped does the game accept keyboard input.

My suggestion: 
 1) Capture the keyboard right from the start
 2) If nr1 doesn't work at least make it so that when the screen is tapped, the keyboard is captured.
 
 thanks!
 
 p.s.   [My embedded game to show that keyboard is not captured](https://www.proofofconcept.nl/portfolio/hoi/)

**Comment by mithrendal** [comment] 2022-11-22 19:52
Oh what a lovely creature ... is its name Hoi ? 

![image](https://user-images.githubusercontent.com/17108995/203407256-83550898-ed88-48b2-9660-631518076335.png)

can I feed it ?


you are right it is really damn hard ... is there a way to switch music off and get sounds when it runs and jumps ? Did you know that vAmigaWeb supports savepoints ... so called snapshots ? What we could do later is add action buttons liked to a hotkey which save a snapshot and another hotkey to restore snapshots ... this way even hard games are easy to master ... 

>ONLY when the bottom gray bar is tapped does the game accept keyboard input.

😬 I can not reproduce this on desktop browsers ... your page works correct in chrome/FF and edge ... i.e. keyboard works immediately when switching the Hoi ingame pal/ntsc choice 

on mobile safari it works with touch ... could not test my bluetooth keyboard because its non-rechargebal batteries are empty, have to buy new ones first... did you produce this issue on a mobile browser ?  

>1. Capture the keyboard right from the start

I already do see here ...
https://github.com/vAmigaWeb/vAmigaWeb/blob/9945d37e7501ce97bbc2655f5286368f053d9a5f/js/vAmiga_ui.js#L3115

**Comment by rhinoid** [comment] 2022-11-22 20:00
hmmm

So I tried it on the Mac in Safari. There the keyboard is weird as I described.
But I installed Chrome (on the Mac) and here it doesn't even boot. It keep spinning with the text: "Booting into vAmiga WebEdition..."

p.s. Sorry if I'm responding slower the coming days. I think I'm coming down with flue/corona/something 😓


The little fella is indeed called 'Hoi' and is happy to be fed!
Waypoints sound perfect. There is a trainer in it but to activate it you have to perform gymnastics which on the Amiga was already hard, and here it's impossible. So waypoints on the best spots on the levels sound awesome.

**Comment by mithrendal** [comment] 2022-11-22 20:44
I will check on the mac ... which MacOS ?

>I think I'm coming down with flue/corona/something 😓

drink much .... hot water !! and keep sleeping ... take care !

**Comment by mithrendal** [comment] 2022-11-22 20:53
👍 reproduced the issue on macOs 12.6.1 with safari 16.1

**Comment by rhinoid** [comment] 2022-11-23 09:07
My appologies. My javascript skills are beyond poor. Where would I put this?  Just at a random place on the page in a script tag? Or at a specific place/location?

**Comment by mithrendal** [comment] 2022-11-23 11:03
this gets very hacky ... and should not be a final solution ... its more a step to a fix .... so I would suggest you to just place the following setTimeout-dommand directly after the player.load command

```javascript
            vAmigaWeb_player.load(this,encodeURIComponent(JSON.stringify(config)));
            setTimeout(()=>document.activeElement.parentElement.click(),600); //<--- make a click outside the iframe to get keyboard events flowing
```

**Comment by rhinoid** [comment] 2022-11-23 13:52
Hi,
Unfortunately both solutions don't work for me. I have the feeling it might be the 'select a disk to mount' popup which could be interfering? Are you testing with a zip?

**Comment by mithrendal** [comment] 2022-11-23 16:12
I will look into the select disk to mount ....

**Comment by mithrendal** [comment] 2022-11-23 16:19
👍this is a good catch !!! when the zip dialog comes up and is closed it is blocking the keyboard ... other dialogs like snapshot or action buttons dialog do not make trouble just the zip dialog... that should be easy to fix ... stay tuned

**Comment by mithrendal** [comment] 2022-11-23 19:55
fixed in vAmigaWeb 😎 with your help !

just pushed out version ui 2022_11_23

**Comment by rhinoid** [comment] 2022-11-24 08:43
Cool!

Anything specific I need to do to get that version?   I now have:  <script src="https://vAmigaWeb.github.io/js/vAmigaWeb_player.js"></script> in my page. But I think that still loads the old version

**Comment by mithrendal** [comment] 2022-11-24 08:57
should be automatic 

i.e. upon clicking on your hoi teaser image it normally loads the PWA (progressive web app) from your browser cache (as usual) ... plus a new service worker is loaded too from the github.io server .. that service worker will be installed but is not active yet. 

upon the next  start the new service worker becomes active and a new version dialog pops up. where you can upgrade to the new version...or stay on the older version.

**Comment by mithrendal** [comment] 2022-11-24 10:15
very cool ! I close this and make a new issue for the upgrade dialog which should stay on top of the zip file dialog ... and not vice versa as it is now ...

**Closed by mithrendal** 2022-11-24 10:15 UTC
